### ISSUE TITLE
dkms fails to recompile cecosec module

### ISSUE THREAD

**Issue by rripio** [ektor5/secocec#7]
Hello,

I'm using secocec on a UDOO x86 with debian testing. It works perfectly with a 5.2.0-3-amd64 kernel.

Whenever there's a new kernel update dkms fail to recompile the secocec module with this message:

_/etc/kernel/header_postinst.d/dkms:
dkms: running auto installation service for kernel 5.5.0-1-amd64:secocec/1.0 autoinstall failed due to missing dependencies: cec_

This has happened with every version newer than the aforementioned 5.2.0-3-amd64. As of today, compilation has failed with update to 5.5.0-1-amd64 debian kernel packet.

I wanted to make you aware of this issue, and I wish that you are safe and sound.

Roberto

**Comment by ektor5** [comment]
Hi @rripio ,
Thanks for reaching out,
Yes, this repo was a bit outdated since Kernel 5.3, also because it was included inside the main tree, so the dkms procedure is not necessary anymore.
Happy to know you are still using this. :)

Anyway, today I had the time to dedicate to this and I've updated this repo with the new compatibility commits from the torvalds/linux tree.
Checking out the latest commit should fix the errors.

Let me know and thanks for the support,
Ettore
